name: object-detection
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - pillow=8.2.0
  - python=3.7.10
  - opencv=4.5.*
  - selenium=3.141.0
  - requests=2.25.1 
  - libwebp=1.2.0
  - pandas=1.1.*
  - matplotlib=3.3.*
  - scikit-learn=0.19.*
  - jupyterlab=2.2.*
  - seaborn=0.11.*
  - jupyterlab
  - pytorch=1.7.0
  - torchvision=0.8.0
  - cudatoolkit=10.2
  - pip=20.2.*
  - pip:
      - requests-toolbelt==0.9.*
      - gdown==3.12.*
      - tensorboard==2.4.*
      - PyYAML==5.3.*
      - uvicorn==0.12.*
      - fastapi==0.61.*
      - imutils==0.5.*